name: poll-craft
recipe: drupal11

config:
  webroot: web
  php: '8.3'
  via: nginx
  xdebug: true

services:
  appserver:
    xdebug: true
    config:
      php: .lando/php.ini
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        DRUSH_OPTIONS_URI: "https://poll-craft.lndo.site/"
        REDIS_HOST: redis
        APP_ENV: "local"
        
  database:
    type: mariadb:10.11
    creds:
      user: drupal
      password: drupal
      database: drupal
      
  phpmyadmin:
    type: phpmyadmin:5.2
    hosts:
      - database
      
  redis:
    type: redis:7

tooling:
  drush:
    service: appserver
    cmd: drush
    
  composer:
    service: appserver
    cmd: composer
    
  phpstan:
    service: appserver
    cmd: ./vendor/bin/phpstan analyze --memory-limit=1G
    description: Run PHPStan static analysis
    
  phpcs:
    service: appserver
    cmd: ./vendor/bin/phpcs
    description: Check coding standards
    
  phpcbf:
    service: appserver
    cmd: ./vendor/bin/phpcbf --standard=Drupal,DrupalPractice
    description: Fix coding standards

  redis-cli:
    service: redis
    cmd: redis-cli
    
  redis-flush:
    service: redis
    cmd: redis-cli FLUSHALL
    description: Clear all Redis cache
    
  xdebug-on:
    service: appserver
    description: Enable xdebug
    cmd: "docker-php-ext-enable xdebug && kill -USR2 1"
    user: root
    
  xdebug-off:
    service: appserver
    description: Disable xdebug
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 1"
    user: root